before_script:
    - apt-get update
    - apt-get install -y python3.8 python3.8-dev python3-pip
    - python3.8 -m pip install pytest setuptools textx matplotlib statistics numpy
    - python3.8 -m pip install pandas
    - git clone https://github.com/Shoobx/python-graph.git
    - cd "python-graph/core/" && python3.8 ./setup.py install
    - cd ../..
    - cd packages/markovchains
    - python3.8 -m pip install .
    - cd ../dataflow
    - python3.8 -m pip install .
    - cd ../finitestateautomata
    - python3.8 -m pip install .


stages:
    - test

test:
    stage: test
    tags:
        - Ubuntu2004-64bit
    script:
        - cd packages/modeltest
        - python3.8 -m pip install .
        - cd ../markovchains
        - python3.8 -m pytest . -v -l
        - cd ../dataflow
        - python3.8 -m pytest . -v -l
        - cd ../finitestateautomata
        - python3.8 -m pytest . -v -l

variables:
    GIT_SUBMODULE_STRATEGY: recursive
