before_script:
    - apt-get update
    - apt-get install -y python3.9 python3.9-dev python3-pip
    - python3.9 -m pip install pytest setuptools textx matplotlib statistics
    - python3.9 -m pip install pandas
    - git clone https://github.com/Shoobx/python-graph.git
    - cd "python-graph/core/" && python3.9 ./setup.py install
    - cd ../..
    - cd packages/markovchains
    - python3.9 -m pip install .
    - cd ../dataflow
    - python3.9 -m pip install .
    - cd ../finitestateautomata
    - python3.9 -m pip install .
    - cd ../..


stages:
    - test

test:
    stage: test
    tags:
        - Ubuntu2004-64bit
    script:
        - cd packages/modeltest
        - python3.9 -m pip install .
        - cd ../markovchains
        - python3.9 -m pytest . -v -l
        - cd ../dataflow
        - python3.9 -m pytest . -v -l
        - cd ../finitestateautomata
        - python3.9 -m pytest . -v -l
        - cd ../markovchains
        - python3.9 -m pip install coverage
        - coverage run -m pytest . -v -l
        - coverage html
        - cd ../dataflow
        - coverage run -m pytest . -v -l
        - coverage html
        - cd ../finitestateautomata
        - coverage run -m pytest . -v -l
        - coverage html
        - pwd
    artifacts:
      expire_in: 14d
      when: always
      paths:
      - packages/finitestateautomata/htmlcov/
      - packages/markovchains/htmlcov/
      - packages/dataflow/htmlcov/



variables:
    GIT_SUBMODULE_STRATEGY: recursive
